## API HTTP Client

### Method to test OpenAI API
POST http://localhost:8080/api/gpt
Content-Type: application/json

{
  "data": 
    {
      "prompt": "Cambio amortiguador"
    }
}

### Method to create a user
POST http://localhost:8081/api/users/register
Content-Type: application/json

{
  "name": "test",
  "email": "ricardo5@gmail.com",
  "password": "supersegura123"
}

### Method to log a user
POST http://localhost:8081/api/users/login
Content-Type: application/json

{
  "email": "ricardo5@gmail.com",
  "password": "supersegura123"
}

POST http://localhost:8081/api/users/login
Content-Type: application/json

{
  "email": "ricardo5@gmail.com",
  "password": "supersegura123"
}

### Method to check if the API is running
GET http://localhost:8080/api/
